import { Account, Category, CreditCard, Transaction, FinancialGoal, Budget } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  // Despesas
  { id: 'cat-exp-1', name: 'Alimentação', type: 'EXPENSE', icon: 'Utensils', color: '#EF4444', is_default: true },
  { id: 'cat-exp-2', name: 'Supermercado', type: 'EXPENSE', icon: 'ShoppingCart', color: '#F97316', is_default: true },
  { id: 'cat-exp-3', name: 'Moradia', type: 'EXPENSE', icon: 'Home', color: '#3B82F6', is_default: true },
  { id: 'cat-exp-4', name: 'Energia Elétrica', type: 'EXPENSE', icon: 'Zap', color: '#EAB308', is_default: true },
  { id: 'cat-exp-5', name: 'Internet e TV', type: 'EXPENSE', icon: 'Wifi', color: '#6366F1', is_default: true },
  { id: 'cat-exp-6', name: 'Transporte', type: 'EXPENSE', icon: 'Car', color: '#8B5CF6', is_default: true },
  { id: 'cat-exp-7', name: 'Combustível', type: 'EXPENSE', icon: 'Fuel', color: '#EC4899', is_default: true },
  { id: 'cat-exp-8', name: 'Saúde e Farmácia', type: 'EXPENSE', icon: 'HeartPulse', color: '#10B981', is_default: true },
  { id: 'cat-exp-9', name: 'Lazer e Streaming', type: 'EXPENSE', icon: 'Film', color: '#F43F5E', is_default: true },
  { id: 'cat-exp-10', name: 'Assinaturas', type: 'EXPENSE', icon: 'CreditCard', color: '#A855F7', is_default: true },
  { id: 'cat-exp-11', name: 'Outras Despesas', type: 'EXPENSE', icon: 'MoreHorizontal', color: '#64748B', is_default: true },
  
  // Receitas
  { id: 'cat-inc-1', name: 'Salário', type: 'INCOME', icon: 'Banknote', color: '#10B981', is_default: true },
  { id: 'cat-inc-2', name: 'Freelance', type: 'INCOME', icon: 'Briefcase', color: '#06B6D4', is_default: true },
  { id: 'cat-inc-3', name: 'Investimentos', type: 'INCOME', icon: 'TrendingUp', color: '#3B82F6', is_default: true },
  { id: 'cat-inc-4', name: 'Renda Extra', type: 'INCOME', icon: 'PlusCircle', color: '#F59E0B', is_default: true },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-1',
    user_id: 'demo-user',
    name: 'Conta Principal Nubank',
    institution: 'Nubank',
    type: 'DIGITAL',
    initial_balance: 1500.00,
    current_balance: 3850.00,
    color: '#8B5CF6',
    is_active: true,
  },
  {
    id: 'acc-2',
    user_id: 'demo-user',
    name: 'Banco Itaú Corrente',
    institution: 'Itaú',
    type: 'CHECKING',
    initial_balance: 800.00,
    current_balance: 1200.00,
    color: '#F97316',
    is_active: true,
  },
  {
    id: 'acc-3',
    user_id: 'demo-user',
    name: 'Carteira Física',
    institution: 'Dinheiro',
    type: 'WALLET',
    initial_balance: 200.00,
    current_balance: 150.00,
    color: '#10B981',
    is_active: true,
  },
];

export const INITIAL_CREDIT_CARDS: CreditCard[] = [
  {
    id: 'card-1',
    user_id: 'demo-user',
    name: 'Nubank Ultravioleta',
    bank: 'Nubank',
    credit_limit: 8000.00,
    closing_day: 12,
    due_day: 20,
    color: '#8B5CF6',
  },
  {
    id: 'card-2',
    user_id: 'demo-user',
    name: 'Itaú Click Visa',
    bank: 'Itaú',
    credit_limit: 5000.00,
    closing_day: 25,
    due_day: 5,
    color: '#EA580C',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    user_id: 'demo-user',
    description: 'Salário Mensal',
    amount: 6500.00,
    type: 'INCOME',
    category_id: 'cat-inc-1',
    account_id: 'acc-1',
    transaction_date: '2026-08-05',
    status: 'RECEIVED',
    payment_method: 'TRANSFER',
    notes: 'Pagamento referente ao mês de Agosto',
  },
  {
    id: 'tx-2',
    user_id: 'demo-user',
    description: 'Projeto Freelance Design UI',
    amount: 1300.00,
    type: 'INCOME',
    category_id: 'cat-inc-2',
    account_id: 'acc-1',
    transaction_date: '2026-08-12',
    status: 'RECEIVED',
    payment_method: 'PIX',
    notes: 'Entrega final do protótipo web',
  },
  {
    id: 'tx-3',
    user_id: 'demo-user',
    description: 'Supermercado Pão de Açúcar',
    amount: 520.00,
    type: 'EXPENSE',
    category_id: 'cat-exp-2',
    account_id: 'acc-1',
    transaction_date: '2026-08-08',
    status: 'PAID',
    payment_method: 'DEBIT_CARD',
    notes: 'Compras do mês',
  },
  {
    id: 'tx-4',
    user_id: 'demo-user',
    description: 'Combustível Posto Shell',
    amount: 280.00,
    type: 'EXPENSE',
    category_id: 'cat-exp-7',
    account_id: 'acc-2',
    transaction_date: '2026-08-14',
    status: 'PAID',
    payment_method: 'PIX',
    notes: 'Tanque cheio',
  },
  {
    id: 'tx-5',
    user_id: 'demo-user',
    description: 'Conta de Energia Elétrica (Enel)',
    amount: 230.00,
    type: 'EXPENSE',
    category_id: 'cat-exp-4',
    account_id: 'acc-1',
    transaction_date: '2026-08-20',
    due_date: '2026-08-20',
    status: 'PENDING',
    payment_method: 'BOLETO',
    notes: 'Vence dia 20/08',
  },
  {
    id: 'tx-6',
    user_id: 'demo-user',
    description: 'Internet Fibra Óptica',
    amount: 120.00,
    type: 'EXPENSE',
    category_id: 'cat-exp-5',
    account_id: 'acc-1',
    transaction_date: '2026-08-22',
    due_date: '2026-08-22',
    status: 'PENDING',
    payment_method: 'PIX',
    notes: 'Vence dia 22/08',
  },
  {
    id: 'tx-7',
    user_id: 'demo-user',
    description: 'Assinatura Netflix Premium',
    amount: 44.90,
    type: 'EXPENSE',
    category_id: 'cat-exp-10',
    account_id: 'acc-1',
    transaction_date: '2026-08-10',
    status: 'PAID',
    payment_method: 'CREDIT_CARD',
    notes: 'Cobrança automática',
  },
  {
    id: 'tx-8',
    user_id: 'demo-user',
    description: 'Aluguel do Apartamento',
    amount: 1800.00,
    type: 'EXPENSE',
    category_id: 'cat-exp-3',
    account_id: 'acc-1',
    transaction_date: '2026-08-05',
    status: 'PAID',
    payment_method: 'TRANSFER',
    notes: 'Pago pontualmente',
  },
];

export const INITIAL_GOALS: FinancialGoal[] = [
  {
    id: 'goal-1',
    user_id: 'demo-user',
    title: 'Reserva de Emergência',
    target_amount: 15000.00,
    current_amount: 9800.00,
    deadline: '2026-12-31',
    icon: 'ShieldCheck',
    color: '#10B981',
    is_completed: false,
  },
  {
    id: 'goal-2',
    user_id: 'demo-user',
    title: 'Viagem de Férias',
    target_amount: 10000.00,
    current_amount: 4500.00,
    deadline: '2027-02-15',
    icon: 'Plane',
    color: '#3B82F6',
    is_completed: false,
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bg-1',
    user_id: 'demo-user',
    category_id: 'cat-exp-2',
    month: 8,
    year: 2026,
    amount_limit: 1000.00,
    spent_amount: 520.00,
  },
  {
    id: 'bg-2',
    user_id: 'demo-user',
    category_id: 'cat-exp-7',
    month: 8,
    year: 2026,
    amount_limit: 600.00,
    spent_amount: 280.00,
  },
];
